"""Stable public CRUD facade.

This module preserves the legacy import contract and monkeypatch seams used by
older callers and tests. New architecture work should prefer `src.application`,
`src.domain`, `src.persistence`, and `src.workers` directly.
"""

from __future__ import annotations

import sys
import types

from .architecture_contracts import COMPATIBILITY_MODULE_CONTRACTS, CRUD_FACADE_ROUTE_API
from . import crud_claims as _crud_claims_module
from . import crud_consequences as _crud_consequences_module
from . import crud_context as _crud_context_module
from . import crud_core as _crud_core_module
from . import crud_embeddings_ops as _crud_embeddings_ops_module
from . import crud_entities as _crud_entities_module
from . import crud_graph_ops as _crud_graph_ops_module
from . import crud_lore_adaptation as _crud_lore_adaptation_module
from . import crud_movement as _crud_movement_module
from . import outbox_runtime as _outbox_runtime_module
from . import crud_patch_apply as _crud_patch_apply_module
from . import crud_planning as _crud_planning_module
from . import crud_profiles as _crud_profiles_module
from . import crud_shared as _crud_shared_module
from . import crud_telemetry as _crud_telemetry_module
from . import crud_turns_logic as _crud_turns_logic_module

from .crud_shared import (
    PatchValidationResult,
    PreparedObjectCreateOp,
    TurnPlanResult,
    _acquire_session_turn_lock,
    _build_session_snapshot_dump,
    _clear_pending_turn_locked,
    _close_player_active_located_in_links,
    _coerce_time_scale_minutes,
    _count_json_tokens,
    _count_text_tokens,
    _get_active_link,
    _get_active_located_in_links,
    _get_latest_located_in_link,
    _get_object,
    _get_pending_turn_started_at,
    _get_player_current_zone_id,
    _get_session_player_object_id,
    _infer_actor_zone_id,
    _is_pending_turn_stale,
    _is_session_turn_runtime_lock_held,
    _is_true,
    _normalize_claim_id_list,
    _normalize_json_preview,
    _normalize_json_preview_by_tokens,
    _normalize_time_payload,
    _parse_datetime_utc,
    _require_object,
    _require_session,
    _resolve_object_ref,
    _safe_int,
    _sanitize_object_data_for_context,
    _session_turn_lock_key,
    _session_turn_runtime_lock,
    _session_turn_runtime_lock_key,
    _session_turn_runtime_lock_supported,
    _recover_abandoned_pending_turn_locked,
    _to_jsonable,
    _truncate_text,
    _truncate_text_to_tokens,
)
from .crud_profiles import (
    _build_faction_profile_text,
    _build_item_profile_text,
    _build_npc_profile_text,
    _build_player_profile_text,
    _build_quest_profile_text,
    _build_zone_profile_text,
    _clear_profile_synth_cache,
    _should_refresh_item_or_faction_profile_embedding,
    _should_refresh_npc_profile_embedding,
    _should_refresh_player_profile_embedding,
    _should_refresh_quest_profile_embedding,
    _should_refresh_zone_profile_embedding,
)
from .crud_embeddings_ops import (
    MEMORY_EVENT_OBJECT_TYPE,
    MEMORY_FACT_OBJECT_TYPE,
    _build_link_context_snippet,
    _coerce_importance,
    _extract_claim_text,
    _extract_link_context_text,
    _list_active_link_context_snippets,
    _maybe_embed_texts,
    _normalize_memory_text,
    _refresh_link_context_embedding,
    _store_memory_candidates,
    _upsert_claim_text_embedding,
    _upsert_faction_profile_embedding,
    _upsert_item_profile_embedding,
    _upsert_link_context_embedding,
    _upsert_npc_profile_embedding,
    _upsert_object_embedding,
    _upsert_player_profile_embedding,
    _upsert_quest_profile_embedding,
    _upsert_zone_profile_embedding,
)
from .crud_context import (
    CHRONICLE_INPUT_NAMESPACE,
    CHRONICLE_OUTPUT_NAMESPACE,
    NARRATIVE_SPINE_OBJECT_TYPE,
    SESSION_SUMMARY_LIVE_TURNS,
    SESSION_SUMMARY_OBJECT_TYPE,
    _SPINE_UPDATER_MAX_TOKENS,
    _apply_elastic_field_budgets,
    _apply_unified_context_scoring,
    _build_embedding_snippet,
    _build_event_embedding_line,
    _build_input_embedding_snippet,
    _build_reaction_hints,
    _build_relevance_query_text,
    _build_turn_context_pack,
    _build_turn_variants_for_context,
    _build_zone_npc_knowledge,
    _collect_embedding_candidates,
    _embed_query_for_relevance,
    _enrich_reaction_hints,
    _ensure_world_prompt_chunks_indexed,
    _get_latest_narrative_spine_row,
    _get_player_inventory,
    _get_player_location_history,
    _get_recent_ai_text_for_relevance,
    _get_recent_scene_entities_for_relevance,
    _get_relevant_player_for_input,
    _list_active_npc_claim_links_for_knowledge,
    _list_active_zone_actor_ids,
    _list_one_hop_link_candidates_for_context,
    _list_orphaned_items_for_context,
    _list_recent_turn_payload_for_spine,
    _list_relevant_claims_for_input,
    _list_relevant_factions_for_input,
    _list_relevant_items_for_input,
    _list_relevant_links_for_input,
    _list_relevant_memories_for_input,
    _list_relevant_npcs_for_input,
    _list_relevant_objects_for_input,
    _list_relevant_quests_for_input,
    _list_relevant_world_prompt_chunks,
    _list_semantically_relevant_turn_indices,
    _list_turn_event_embedding_lines,
    _list_zone_npcs_with_relationships,
    _list_zone_recent_claims,
    _merge_npc_knowledge_subjects,
    _render_turn_ai_text,
    _resolve_exact_name_object_ids_for_context,
    _serialize_patch_ops,
    _split_world_prompt_chunks,
    _summarize_world_prompt_chunks,
    _update_narrative_spine,
)
from .crud_planning import (
    PATCH_OP_LIST_ADAPTER,
    _build_plan_from_debug_patch,
    _call_deepseek_patch_generator,
    _call_librarian,
    _call_narrator,
    _call_post_apply_narrator,
    _call_narrator_text_only,
    _collect_refs,
    _parse_narrator_response,
    _parse_world_intent_response,
    _resolve_turn_plan,
    _resolve_turn_plan_from_request,
    _resolve_turn_plan_legacy,
    _resolve_turn_plan_state_first,
    _resolve_turn_plan_split,
    _toposort_patch_ops,
    _validate_patch_ops,
)
from .crud_patch_apply import (
    PatchApplyResult,
    _find_ephemeral_npc_dedup_candidate,
    _find_global_object_dedup_candidate,
    _find_global_zone_dedup_candidate,
    _find_persistent_npc_dedup_candidate,
    _prepare_object_create_chunk,
    apply_patch_ops,
)
from .crud_entities import (
    create_link,
    create_object,
    create_session_snapshot,
    create_session_with_defaults,
    delete_session,
    get_object,
    get_session,
    get_session_snapshot,
    get_session_token_stats,
    index_turn_embedding,
    list_events,
    list_links,
    list_objects,
    list_session_snapshots,
    reindex_world_prompt,
    semantic_retrieve,
)
from .crud_telemetry import (
    activate_system_prompt,
    get_llm_telemetry_summary,
    list_active_system_prompts,
    list_outbox_events,
    list_session_llm_telemetry,
)
from .crud_consequences import (
    COOLDOWN_TURNS,
    MAX_CONSEQUENCE_CHAIN_DEPTH,
    MAX_CONSEQUENCE_WINDOW_SPAN,
    PRIORITY_WEIGHT,
    apply_consequence_results,
    detect_structural_signals,
    enqueue_consequences,
    get_object_by_type,
    resolve_applied_op_refs,
    select_due_consequences,
    select_due_consequences_from_state_json,
)
from .crud_graph_ops import (
    apply_pending_graph_ops,
    get_pending_graph_ops,
    maybe_run_graph_health_check,
    run_graph_health_check,
)
from .crud_claims import (
    create_claim,
)
from .crud_lore_adaptation import (
    answer_lore_gap,
    auto_resolve_lore_gaps,
    get_lore_adaptation,
    get_lore_turn_blocker,
    upload_lore,
)
from .crud_movement import (
    _move_player_locked,
    move_player,
)
from .crud_turns_logic import (
    _allocate_turn,
    _apply_turn_plan,
    _coerce_turn_weight_value,
    _derive_turn_weight,
    _recover_stuck_pending_turn,
    _run_turn_locked,
    patch_turn,
    recover_pending_turn,
    run_turn,
)
from .crud_core import (
    LINK_TEXT_DATA_KEYS,
    RELEVANCE_QUERY_EMBED_INSTRUCTION,
    WORLD_PROMPT_EMBED_INSTRUCTION,
    _PlanBuildFailed,
    _SUMMARIZER_SYSTEM,
    _build_degraded_turn_plan,
    _classify_plan_degradation,
    _extract_applied_ops_from_ai_json,
    _repair_player_location_after_pending_turn_recovery,
    _summarize_turn_for_indexing,
    cleanup_ephemeral_npcs,
    get_relationship_graph,
    get_session_diff,
    get_session_timeline,
    logger,
)

COMPATIBILITY_MODULE_CONTRACT = COMPATIBILITY_MODULE_CONTRACTS[__name__]
PUBLIC_ROUTE_API = CRUD_FACADE_ROUTE_API

__all__ = [
    "CHRONICLE_INPUT_NAMESPACE",
    "CHRONICLE_OUTPUT_NAMESPACE",
    "COOLDOWN_TURNS",
    "LINK_TEXT_DATA_KEYS",
    "MAX_CONSEQUENCE_CHAIN_DEPTH",
    "MAX_CONSEQUENCE_WINDOW_SPAN",
    "NARRATIVE_SPINE_OBJECT_TYPE",
    "PATCH_OP_LIST_ADAPTER",
    "PRIORITY_WEIGHT",
    "PatchValidationResult",
    "PreparedObjectCreateOp",
    "RELEVANCE_QUERY_EMBED_INSTRUCTION",
    "SESSION_SUMMARY_LIVE_TURNS",
    "SESSION_SUMMARY_OBJECT_TYPE",
    "TurnPlanResult",
    "WORLD_PROMPT_EMBED_INSTRUCTION",
    "_PlanBuildFailed",
    "_SPINE_UPDATER_MAX_TOKENS",
    "_SUMMARIZER_SYSTEM",
    "_acquire_session_turn_lock",
    "_allocate_turn",
    "_apply_elastic_field_budgets",
    "_apply_turn_plan",
    "_apply_unified_context_scoring",
    "_build_degraded_turn_plan",
    "_build_embedding_snippet",
    "_build_event_embedding_line",
    "_build_faction_profile_text",
    "_build_input_embedding_snippet",
    "_build_item_profile_text",
    "_build_link_context_snippet",
    "_build_npc_profile_text",
    "_build_plan_from_debug_patch",
    "_build_player_profile_text",
    "_build_quest_profile_text",
    "_build_reaction_hints",
    "_build_relevance_query_text",
    "_build_session_snapshot_dump",
    "_build_turn_context_pack",
    "_build_zone_npc_knowledge",
    "_build_zone_profile_text",
    "_call_deepseek_patch_generator",
    "_call_librarian",
    "_call_narrator",
    "_call_narrator_text_only",
    "_classify_plan_degradation",
    "_clear_pending_turn_locked",
    "_clear_profile_synth_cache",
    "_close_player_active_located_in_links",
    "_coerce_importance",
    "_coerce_time_scale_minutes",
    "_coerce_turn_weight_value",
    "_collect_embedding_candidates",
    "_collect_refs",
    "_count_json_tokens",
    "_count_text_tokens",
    "_derive_turn_weight",
    "_embed_query_for_relevance",
    "_enrich_reaction_hints",
    "_ensure_world_prompt_chunks_indexed",
    "_extract_applied_ops_from_ai_json",
    "_extract_claim_text",
    "_extract_link_context_text",
    "_find_ephemeral_npc_dedup_candidate",
    "_find_global_object_dedup_candidate",
    "_find_global_zone_dedup_candidate",
    "_find_persistent_npc_dedup_candidate",
    "_get_active_link",
    "_get_active_located_in_links",
    "_get_latest_located_in_link",
    "_get_latest_narrative_spine_row",
    "_get_object",
    "_get_pending_turn_started_at",
    "_get_player_current_zone_id",
    "_get_player_inventory",
    "_get_player_location_history",
    "_get_recent_ai_text_for_relevance",
    "_get_recent_scene_entities_for_relevance",
    "_get_relevant_player_for_input",
    "_get_session_player_object_id",
    "_infer_actor_zone_id",
    "_is_pending_turn_stale",
    "_is_session_turn_runtime_lock_held",
    "_is_true",
    "_list_active_link_context_snippets",
    "_list_active_npc_claim_links_for_knowledge",
    "_list_active_zone_actor_ids",
    "_list_one_hop_link_candidates_for_context",
    "_list_orphaned_items_for_context",
    "_list_recent_turn_payload_for_spine",
    "_list_relevant_claims_for_input",
    "_list_relevant_factions_for_input",
    "_list_relevant_items_for_input",
    "_list_relevant_links_for_input",
    "_list_relevant_memories_for_input",
    "_list_relevant_npcs_for_input",
    "_list_relevant_objects_for_input",
    "_list_relevant_quests_for_input",
    "_list_relevant_world_prompt_chunks",
    "_list_semantically_relevant_turn_indices",
    "_list_turn_event_embedding_lines",
    "_list_zone_npcs_with_relationships",
    "_list_zone_recent_claims",
    "_maybe_embed_texts",
    "_merge_npc_knowledge_subjects",
    "_move_player_locked",
    "_normalize_claim_id_list",
    "_normalize_json_preview",
    "_normalize_json_preview_by_tokens",
    "_normalize_memory_text",
    "_normalize_time_payload",
    "_parse_datetime_utc",
    "_parse_narrator_response",
    "_parse_world_intent_response",
    "_prepare_object_create_chunk",
    "_recover_stuck_pending_turn",
    "_refresh_link_context_embedding",
    "_render_turn_ai_text",
    "_repair_player_location_after_pending_turn_recovery",
    "_require_object",
    "_require_session",
    "_resolve_exact_name_object_ids_for_context",
    "_resolve_object_ref",
    "_resolve_turn_plan",
    "_resolve_turn_plan_from_request",
    "_resolve_turn_plan_legacy",
    "_resolve_turn_plan_state_first",
    "_resolve_turn_plan_split",
    "_run_turn_locked",
    "_safe_int",
    "_sanitize_object_data_for_context",
    "_serialize_patch_ops",
    "_recover_abandoned_pending_turn_locked",
    "_session_turn_lock_key",
    "_session_turn_runtime_lock",
    "_session_turn_runtime_lock_key",
    "_session_turn_runtime_lock_supported",
    "_should_refresh_item_or_faction_profile_embedding",
    "_should_refresh_npc_profile_embedding",
    "_should_refresh_player_profile_embedding",
    "_should_refresh_quest_profile_embedding",
    "_should_refresh_zone_profile_embedding",
    "_split_world_prompt_chunks",
    "_summarize_turn_for_indexing",
    "_summarize_world_prompt_chunks",
    "_to_jsonable",
    "_toposort_patch_ops",
    "_truncate_text",
    "_truncate_text_to_tokens",
    "_update_narrative_spine",
    "_upsert_claim_text_embedding",
    "_upsert_faction_profile_embedding",
    "_upsert_item_profile_embedding",
    "_upsert_link_context_embedding",
    "_upsert_npc_profile_embedding",
    "_upsert_object_embedding",
    "_upsert_player_profile_embedding",
    "_upsert_quest_profile_embedding",
    "_upsert_zone_profile_embedding",
    "_validate_patch_ops",
    "activate_system_prompt",
    "_call_post_apply_narrator",
    "answer_lore_gap",
    "apply_consequence_results",
    "apply_patch_ops",
    "apply_pending_graph_ops",
    "auto_resolve_lore_gaps",
    "cleanup_ephemeral_npcs",
    "create_claim",
    "create_link",
    "create_object",
    "create_session_snapshot",
    "create_session_with_defaults",
    "delete_session",
    "detect_structural_signals",
    "enqueue_consequences",
    "get_llm_telemetry_summary",
    "get_lore_adaptation",
    "get_lore_turn_blocker",
    "get_object",
    "get_object_by_type",
    "get_pending_graph_ops",
    "get_relationship_graph",
    "get_session",
    "get_session_diff",
    "get_session_snapshot",
    "get_session_timeline",
    "get_session_token_stats",
    "index_turn_embedding",
    "list_active_system_prompts",
    "list_events",
    "list_links",
    "list_objects",
    "list_outbox_events",
    "list_session_llm_telemetry",
    "list_session_snapshots",
    "logger",
    "maybe_run_graph_health_check",
    "move_player",
    "patch_turn",
    "recover_pending_turn",
    "reindex_world_prompt",
    "resolve_applied_op_refs",
    "run_graph_health_check",
    "run_turn",
    "select_due_consequences",
    "select_due_consequences_from_state_json",
    "semantic_retrieve",
    "upload_lore",
]


_FACADE_SYNC_MODULES = (
    _crud_shared_module,
    _crud_profiles_module,
    _crud_embeddings_ops_module,
    _crud_context_module,
    _crud_planning_module,
    _crud_patch_apply_module,
    _crud_entities_module,
    _crud_telemetry_module,
    _crud_consequences_module,
    _crud_graph_ops_module,
    _crud_claims_module,
    _crud_lore_adaptation_module,
    _crud_movement_module,
    _outbox_runtime_module,
    _crud_turns_logic_module,
    _crud_core_module,
)

# Keep facade backward-compatible for tests and monkeypatching code paths:
# expose symbols from internal modules and fan-out attribute overrides to
# underlying modules where call-sites resolve names.
for _module in _FACADE_SYNC_MODULES:
    for _name, _value in vars(_module).items():
        if _name.startswith("__"):
            continue
        globals().setdefault(_name, _value)


class _CrudFacadeModule(types.ModuleType):
    def __setattr__(self, name: str, value: object) -> None:
        super().__setattr__(name, value)
        if name.startswith("__"):
            return
        for module in _FACADE_SYNC_MODULES:
            if hasattr(module, name):
                setattr(module, name, value)


sys.modules[__name__].__class__ = _CrudFacadeModule
